{{- if .Values.prometheus.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "prometheus.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  {{- if .Values.prometheus.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.prometheus.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.prometheus.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
{{- end }}
