{
 "title": "Cluster Resources & Pods",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(istio:namespace_destination_service_name_response_code:istio_requests:rate5m, destination_service_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(deploy:cluster_autoscaler:cpu_current_cores:gauge) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(deploy:cluster_autoscaler:memory_current_bytes:gauge) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(deploy:cluster_autoscaler:nodes_count:gauge{state=\"ready\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(deploy:replicas_available:mean{namespace=\"$namespace\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}