{
 "title": "SLO Details",
 "description": "Details for SLO recorded by Sloth",
 "tags": [
  "service levels",
  "sli",
  "slo",
  "sloth"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(slo:objective:ratio, sloth_service)"
    }
   },
   {
    "name": "state",
    "label": "State",
    "query": {
     "query": "label_values(slo:objective:ratio, state)"
    }
   },
   {
    "name": "slo",
    "query": {
     "query": "label_values(slo:objective:ratio{sloth_service=\"${service}\", state=\"$state\"}, sloth_slo)"
    }
   },
   { "name": "sli_window", "label": "SLI window", "query": "5m,30m,1h,2h,6h,1d,3d,30d" },
   { "name": "min_burning_rate", "label": "Min Burning rate", "query": "1" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exceeded burning rate SLOs ",
   "type": "table",
   "description": "The SLOs that currently are burning more error budget that then available",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{state=\"$state\"} > ${min_burning_rate}"
    }
   ]
  },
  {
   "title": "All burning rate (Filtered >${min_burning_rate}x)",
   "type": "timeseries",
   "description": "The burning rate of the all the Service SLOs",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{state=\"$state\"} > ${min_burning_rate}",
     "legendFormat": "{{sloth_slo}}"
    }
   ]
  },
  { "title": "${service}/${slo}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "slo" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max(slo:sli_error:ratio_rate${sli_window}{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}) OR on() vector(0))",
     "legendFormat": "SLI"
    },
    {
     "expr": "slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "Objective"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sloth_slo_info{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "{{objective_details}}%"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This moment burning % of the budget.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} or on() vector(0)",
     "legendFormat": "Current burning budget %"
    }
   ]
  },
  {
   "type": "stat",
   "description": "A rolling window of the total period (30d) error budget remaining.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    1-(\n    sum_over_time(\n        (\n        sum(slo:sli_error:ratio_rate1h{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}) by (sloth_id, sloth_service, sloth_slo)\n        )[30d:1h]\n    )\n    / on(sloth_id)\n    (\n        max(slo:error_budget:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}) by (sloth_id) *on() group_left() (24 * 30)\n    )\n    )\nor on() vector(1), 0)",
     "legendFormat": "Remaining error budget (30d window)"
    }
   ]
  },
  {
   "title": "Error budget burn chart",
   "type": "timeseries",
   "description": "This graph shows the trailing 30 day budget burn down chart",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    (\n       sum(slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\",prometheus_replica=\"\"}) by (sloth_id, sloth_service, sloth_slo)\n       * on() group_left() (\n         time() >= bool vector(${__from:date:seconds})\n       )\n    )[30d:1h]\n  )\n  / on(sloth_id)\n  (\n    max(slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\",prometheus_replica=\"\"}) by (sloth_id) *on() group_left() (24 * 30)\n  )\n)",
     "legendFormat": "Remaining error budget"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"ticket\"}) OR on() vector(0)",
     "legendFormat": "Warning alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"page\"}) or on() vector(0)",
     "legendFormat": "Critical alert"
    }
   ]
  }
 ]
}