{
 "title": "SLO Overview",
 "description": "A high level view of all Sloth SLOs",
 "tags": [
  "service levels",
  "sli",
  "slo",
  "sloth"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "min_burning_rate", "label": "Min Burning rate", "query": "1" },
   {
    "name": "state",
    "label": "State",
    "query": {
     "query": "label_values(slo:objective:ratio, state)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(slo:error_budget:ratio{state=\"$state\"})",
     "legendFormat": "SLOs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(slo:error_budget:ratio{state=\"$state\"}) by (sloth_service))",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slo:current_burn_rate:ratio{state=\"$state\"})",
     "legendFormat": "Avg burn rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_id!=\"\",sloth_severity=\"ticket\",state=\"$state\"}) OR on() vector(0)",
     "legendFormat": "Warning alerts"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_id!=\"\",sloth_severity=\"page\",state=\"$state\"}) OR on() vector(0)",
     "legendFormat": "Critical alerts"
    }
   ]
  },
  { "title": "SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "All burning rate (Filtered >${min_burning_rate}x)",
   "type": "timeseries",
   "description": "The burning rate of the all the Service SLOs",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{state=\"$state\"} > ${min_burning_rate}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  {
   "title": "Current exceeded burning rate SLOs ",
   "type": "table",
   "description": "The SLOs that currently are burning more error budget that then available",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{state=\"$state\"} > ${min_burning_rate}"
    }
   ]
  },
  {
   "title": "SLOs burn rate state timeline",
   "type": "state-timeline",
   "description": "Shows all the SLOs at the same time burning rate state",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max(slo:current_burn_rate:ratio{state=\"$state\"}) by (sloth_slo, sloth_service)",
     "legendFormat": "{{sloth_service}}/{{sloth_slo}}"
    }
   ]
  },
  {
   "title": "Error Budget remaining 30-day window",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    1-(\n    sum_over_time(\n        (\n        sum(slo:sli_error:ratio_rate1h{state=\"$state\"}) by (sloth_id)\n        )[30d:1h]\n    )\n    / on(sloth_id)\n    (\n        max(slo:error_budget:ratio{state=\"$state\"}) by (sloth_id) *on() group_left() (24 * 30)\n    )\n    )\nor on() vector(1), 0)",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  }
 ]
}