variable "admin_principals" {
  description = "Principals allowed to peform admin actions (default: current account)"
  type        = list(string)
  default     = null
}

variable "workspace_url" {
  description = "URL for the Grafana workspace"
  type        = string
}

variable "initial_api_key" {
  description = "API key generated by a user from the admin panel"
  type        = string
  default     = ""
}

variable "name" {
  type        = string
  description = "Name for the AWS secret"
}

variable "read_principals" {
  description = "Principals allowed to read the secret (default: current account)"
  type        = list(string)
  default     = null
}

variable "tags" {
  description = "Tags which should be applied to created resources"
  default     = {}
  type        = map(string)
}

variable "trust_tags" {
  description = "Tags required on principals accessing the secret"
  type        = map(string)
  default     = {}
}
